FROM node:alpine
WORKDIR '/app'

COPY package.json .
#COPY package-lock.json .

RUN npm install

COPY . .

CMD ["npm", "run", "dev"]
#RUN npm run build
#
#FROM nginx
#EXPOSE 80
#COPY --from=builder_face /app/build /usr/share/nginx/html